name= 'Kantheesh'
print(name[-1:])
print('-----------------------')
print(name[0:9])
print('-----------------------')
print(name[-1:-8])
print('-----------------------')
print(name[-1:7])
print('-----------------------')
print(name[-9:6])
print('-----------------------')
print(name[-2:])
print('-----------------------')
print(name[4:-4])
print('-----------------------')
print(name[5])